server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  mail:
    protocol: ${MAIL_PROTOCOL}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    address: &{MAIL_ADDRESS}

security:
  jwt:
    token:
      secret-key: ${SECURITY_SECRET_KEY}
      expire-length : ${SECURITY_EXPIRE_LENGHT}
